package com.csye6225.spring2020.courseservice.datamodel;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

public class Program {
	private String programId;
	private String programName;
	private ArrayList<Course> courseList;
	
	public Program() {}
	
	public Program(String programId, String programName) {
		this.programId = programId;
		this.programName = programName;
		courseList = new ArrayList<Course>();
	}
	
	public String getProgramId() {
		return programId;
	}
	public String getProgramName() {
		return programName;
	}
	public List<Course> getCourseList(){
		return courseList;
	}
	public void setProgramId(String programId) {
		this.programId = programId;
	}
	public void setProgramName(String programName) {
		this.programName = programName;
	}
	public Course addCourse(Course course) {
		courseList.add(course);
		return course;
	}
	@Override
	public String toString() { 
		return "ProgramId=" + getProgramId() + ", ProgramName=" + getProgramName();
	}
}
