package com.csye6225.spring2020.courseservice.datamodel;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

public class Student {
	private String studentId;
	private String firstName;
	private String lastName;
	private String imgUrl;
	private Program stuProgram;
	
	public Student() {
		
	}
	public Student(String firstName, String lastName,String studentId ,String imgUrl, Program stuProgram) {
		this.firstName = firstName;
		this.imgUrl = imgUrl;
		this.lastName = lastName;
		this.studentId = studentId;
		this.stuProgram = stuProgram;
	}
	
	public String getFirstName() {
		return firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public String getStudentId() {
		return studentId;
	}
	public String getImgUrl() {
		return imgUrl;
	}
	public Program getStuProgram() {
		return stuProgram;
	}
	
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}
	public void setStuProgram(Program stuProgram) {
		this.stuProgram = stuProgram;
	}
	
	@Override
	public String toString() {
		return "StudentId=" + getStudentId() + ", firstName=" + getFirstName()
		+ ", lastName=" + getLastName() + ", StuProgram=" + getStuProgram();
	}
}
